package org.zt.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.ORDER_NO
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.PARK_ID
     *
     * @mbggenerated
     */
    private String parkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.PARK_CODE
     *
     * @mbggenerated
     */
    private String parkCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.PARK_NAME
     *
     * @mbggenerated
     */
    private String parkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.BUSINESSER_ID
     *
     * @mbggenerated
     */
    private String businesserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.BUSINESSER_CODE
     *
     * @mbggenerated
     */
    private String businesserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.GCODE_ID
     *
     * @mbggenerated
     */
    private String gcodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.GOODS_TITLE
     *
     * @mbggenerated
     */
    private String goodsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.MER_GID
     *
     * @mbggenerated
     */
    private String merGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.SERVICE_STIME
     *
     * @mbggenerated
     */
    private Date serviceStime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.SERVICE_ETIME
     *
     * @mbggenerated
     */
    private Date serviceEtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.SERVICE_FEE_TIME
     *
     * @mbggenerated
     */
    private Integer serviceFeeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.CUR_TYPE
     *
     * @mbggenerated
     */
    private Integer curType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.SERVICE_FEE
     *
     * @mbggenerated
     */
    private Integer serviceFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.DEDUCT_FEE
     *
     * @mbggenerated
     */
    private Integer deductFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.DISCOUNT_FEE
     *
     * @mbggenerated
     */
    private Integer discountFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.TRANSPORT_FEE
     *
     * @mbggenerated
     */
    private Integer transportFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.OTHER_FEE
     *
     * @mbggenerated
     */
    private Integer otherFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.TOTAL_FEE
     *
     * @mbggenerated
     */
    private Integer totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.GOPARK_DESC
     *
     * @mbggenerated
     */
    private String goparkDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.NOTIFY_URL
     *
     * @mbggenerated
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.SUBSYSTEM_URL
     *
     * @mbggenerated
     */
    private String subsystemUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.RETCODE
     *
     * @mbggenerated
     */
    private Integer retcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.RETMSG
     *
     * @mbggenerated
     */
    private String retmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.ATTACH
     *
     * @mbggenerated
     */
    private String attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.IS_SHOW
     *
     * @mbggenerated
     */
    private Integer isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.RECEIPT_RECEIVE_TIME
     *
     * @mbggenerated
     */
    private Date receiptReceiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.RECEIPT_ADDR
     *
     * @mbggenerated
     */
    private String receiptAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.ACCESS_TOKEN
     *
     * @mbggenerated
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.TOKEN_TIME
     *
     * @mbggenerated
     */
    private Date tokenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.RECEIPT_OPERATOR
     *
     * @mbggenerated
     */
    private String receiptOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.ACCESS_SOURCE
     *
     * @mbggenerated
     */
    private String accessSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.PAY_TYPE
     *
     * @mbggenerated
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.IS_GET_RECEIPT
     *
     * @mbggenerated
     */
    private Integer isGetReceipt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.IS_UPLOAD
     *
     * @mbggenerated
     */
    private Integer isUpload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.UPLOAD_TIME
     *
     * @mbggenerated
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.IS_OUT_PARK
     *
     * @mbggenerated
     */
    private Integer isOutPark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.COUPON_TYPE
     *
     * @mbggenerated
     */
    private String couponType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.COUPON_VALUE
     *
     * @mbggenerated
     */
    private String couponValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.IS_STAT
     *
     * @mbggenerated
     */
    private Integer isStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.CAR_NO
     *
     * @mbggenerated
     */
    private String carNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.PLATE_COLOR
     *
     * @mbggenerated
     */
    private String plateColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.REFUND_TIME
     *
     * @mbggenerated
     */
    private Date refundTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.SYNC_TIME
     *
     * @mbggenerated
     */
    private Date syncTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.PREFERENTIAL_MODE
     *
     * @mbggenerated
     */
    private String preferentialMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.COUPON_THR_NO
     *
     * @mbggenerated
     */
    private String couponThrNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.COUPON_THR_TYPE
     *
     * @mbggenerated
     */
    private Integer couponThrType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.MEMBER_NO
     *
     * @mbggenerated
     */
    private String memberNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.DEDUCTION
     *
     * @mbggenerated
     */
    private BigDecimal deduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.IS_VALID
     *
     * @mbggenerated
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.IN_ID
     *
     * @mbggenerated
     */
    private String inId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.PREPAY_TIME
     *
     * @mbggenerated
     */
    private Date prepayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.CHANNEL_CODE
     *
     * @mbggenerated
     */
    private String channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.CHANNEL_BUS_CODE
     *
     * @mbggenerated
     */
    private String channelBusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_biz_order.time_end
     *
     * @mbggenerated
     */
    private Date timeEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.ID
     *
     * @return the value of cs_biz_order.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.ID
     *
     * @param id the value for cs_biz_order.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.ORDER_NO
     *
     * @return the value of cs_biz_order.ORDER_NO
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.ORDER_NO
     *
     * @param orderNo the value for cs_biz_order.ORDER_NO
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.USER_ID
     *
     * @return the value of cs_biz_order.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.USER_ID
     *
     * @param userId the value for cs_biz_order.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.PARK_ID
     *
     * @return the value of cs_biz_order.PARK_ID
     *
     * @mbggenerated
     */
    public String getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.PARK_ID
     *
     * @param parkId the value for cs_biz_order.PARK_ID
     *
     * @mbggenerated
     */
    public void setParkId(String parkId) {
        this.parkId = parkId == null ? null : parkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.PARK_CODE
     *
     * @return the value of cs_biz_order.PARK_CODE
     *
     * @mbggenerated
     */
    public String getParkCode() {
        return parkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.PARK_CODE
     *
     * @param parkCode the value for cs_biz_order.PARK_CODE
     *
     * @mbggenerated
     */
    public void setParkCode(String parkCode) {
        this.parkCode = parkCode == null ? null : parkCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.PARK_NAME
     *
     * @return the value of cs_biz_order.PARK_NAME
     *
     * @mbggenerated
     */
    public String getParkName() {
        return parkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.PARK_NAME
     *
     * @param parkName the value for cs_biz_order.PARK_NAME
     *
     * @mbggenerated
     */
    public void setParkName(String parkName) {
        this.parkName = parkName == null ? null : parkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.BUSINESSER_ID
     *
     * @return the value of cs_biz_order.BUSINESSER_ID
     *
     * @mbggenerated
     */
    public String getBusinesserId() {
        return businesserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.BUSINESSER_ID
     *
     * @param businesserId the value for cs_biz_order.BUSINESSER_ID
     *
     * @mbggenerated
     */
    public void setBusinesserId(String businesserId) {
        this.businesserId = businesserId == null ? null : businesserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.BUSINESSER_CODE
     *
     * @return the value of cs_biz_order.BUSINESSER_CODE
     *
     * @mbggenerated
     */
    public String getBusinesserCode() {
        return businesserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.BUSINESSER_CODE
     *
     * @param businesserCode the value for cs_biz_order.BUSINESSER_CODE
     *
     * @mbggenerated
     */
    public void setBusinesserCode(String businesserCode) {
        this.businesserCode = businesserCode == null ? null : businesserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.GCODE_ID
     *
     * @return the value of cs_biz_order.GCODE_ID
     *
     * @mbggenerated
     */
    public String getGcodeId() {
        return gcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.GCODE_ID
     *
     * @param gcodeId the value for cs_biz_order.GCODE_ID
     *
     * @mbggenerated
     */
    public void setGcodeId(String gcodeId) {
        this.gcodeId = gcodeId == null ? null : gcodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.GOODS_TITLE
     *
     * @return the value of cs_biz_order.GOODS_TITLE
     *
     * @mbggenerated
     */
    public String getGoodsTitle() {
        return goodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.GOODS_TITLE
     *
     * @param goodsTitle the value for cs_biz_order.GOODS_TITLE
     *
     * @mbggenerated
     */
    public void setGoodsTitle(String goodsTitle) {
        this.goodsTitle = goodsTitle == null ? null : goodsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.MER_GID
     *
     * @return the value of cs_biz_order.MER_GID
     *
     * @mbggenerated
     */
    public String getMerGid() {
        return merGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.MER_GID
     *
     * @param merGid the value for cs_biz_order.MER_GID
     *
     * @mbggenerated
     */
    public void setMerGid(String merGid) {
        this.merGid = merGid == null ? null : merGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.SERVICE_STIME
     *
     * @return the value of cs_biz_order.SERVICE_STIME
     *
     * @mbggenerated
     */
    public Date getServiceStime() {
        return serviceStime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.SERVICE_STIME
     *
     * @param serviceStime the value for cs_biz_order.SERVICE_STIME
     *
     * @mbggenerated
     */
    public void setServiceStime(Date serviceStime) {
        this.serviceStime = serviceStime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.SERVICE_ETIME
     *
     * @return the value of cs_biz_order.SERVICE_ETIME
     *
     * @mbggenerated
     */
    public Date getServiceEtime() {
        return serviceEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.SERVICE_ETIME
     *
     * @param serviceEtime the value for cs_biz_order.SERVICE_ETIME
     *
     * @mbggenerated
     */
    public void setServiceEtime(Date serviceEtime) {
        this.serviceEtime = serviceEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.SERVICE_FEE_TIME
     *
     * @return the value of cs_biz_order.SERVICE_FEE_TIME
     *
     * @mbggenerated
     */
    public Integer getServiceFeeTime() {
        return serviceFeeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.SERVICE_FEE_TIME
     *
     * @param serviceFeeTime the value for cs_biz_order.SERVICE_FEE_TIME
     *
     * @mbggenerated
     */
    public void setServiceFeeTime(Integer serviceFeeTime) {
        this.serviceFeeTime = serviceFeeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.CUR_TYPE
     *
     * @return the value of cs_biz_order.CUR_TYPE
     *
     * @mbggenerated
     */
    public Integer getCurType() {
        return curType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.CUR_TYPE
     *
     * @param curType the value for cs_biz_order.CUR_TYPE
     *
     * @mbggenerated
     */
    public void setCurType(Integer curType) {
        this.curType = curType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.SERVICE_FEE
     *
     * @return the value of cs_biz_order.SERVICE_FEE
     *
     * @mbggenerated
     */
    public Integer getServiceFee() {
        return serviceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.SERVICE_FEE
     *
     * @param serviceFee the value for cs_biz_order.SERVICE_FEE
     *
     * @mbggenerated
     */
    public void setServiceFee(Integer serviceFee) {
        this.serviceFee = serviceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.DEDUCT_FEE
     *
     * @return the value of cs_biz_order.DEDUCT_FEE
     *
     * @mbggenerated
     */
    public Integer getDeductFee() {
        return deductFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.DEDUCT_FEE
     *
     * @param deductFee the value for cs_biz_order.DEDUCT_FEE
     *
     * @mbggenerated
     */
    public void setDeductFee(Integer deductFee) {
        this.deductFee = deductFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.DISCOUNT_FEE
     *
     * @return the value of cs_biz_order.DISCOUNT_FEE
     *
     * @mbggenerated
     */
    public Integer getDiscountFee() {
        return discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.DISCOUNT_FEE
     *
     * @param discountFee the value for cs_biz_order.DISCOUNT_FEE
     *
     * @mbggenerated
     */
    public void setDiscountFee(Integer discountFee) {
        this.discountFee = discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.TRANSPORT_FEE
     *
     * @return the value of cs_biz_order.TRANSPORT_FEE
     *
     * @mbggenerated
     */
    public Integer getTransportFee() {
        return transportFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.TRANSPORT_FEE
     *
     * @param transportFee the value for cs_biz_order.TRANSPORT_FEE
     *
     * @mbggenerated
     */
    public void setTransportFee(Integer transportFee) {
        this.transportFee = transportFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.OTHER_FEE
     *
     * @return the value of cs_biz_order.OTHER_FEE
     *
     * @mbggenerated
     */
    public Integer getOtherFee() {
        return otherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.OTHER_FEE
     *
     * @param otherFee the value for cs_biz_order.OTHER_FEE
     *
     * @mbggenerated
     */
    public void setOtherFee(Integer otherFee) {
        this.otherFee = otherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.TOTAL_FEE
     *
     * @return the value of cs_biz_order.TOTAL_FEE
     *
     * @mbggenerated
     */
    public Integer getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.TOTAL_FEE
     *
     * @param totalFee the value for cs_biz_order.TOTAL_FEE
     *
     * @mbggenerated
     */
    public void setTotalFee(Integer totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.CREATE_TIME
     *
     * @return the value of cs_biz_order.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.CREATE_TIME
     *
     * @param createTime the value for cs_biz_order.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.GOPARK_DESC
     *
     * @return the value of cs_biz_order.GOPARK_DESC
     *
     * @mbggenerated
     */
    public String getGoparkDesc() {
        return goparkDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.GOPARK_DESC
     *
     * @param goparkDesc the value for cs_biz_order.GOPARK_DESC
     *
     * @mbggenerated
     */
    public void setGoparkDesc(String goparkDesc) {
        this.goparkDesc = goparkDesc == null ? null : goparkDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.NOTIFY_URL
     *
     * @return the value of cs_biz_order.NOTIFY_URL
     *
     * @mbggenerated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.NOTIFY_URL
     *
     * @param notifyUrl the value for cs_biz_order.NOTIFY_URL
     *
     * @mbggenerated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.SUBSYSTEM_URL
     *
     * @return the value of cs_biz_order.SUBSYSTEM_URL
     *
     * @mbggenerated
     */
    public String getSubsystemUrl() {
        return subsystemUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.SUBSYSTEM_URL
     *
     * @param subsystemUrl the value for cs_biz_order.SUBSYSTEM_URL
     *
     * @mbggenerated
     */
    public void setSubsystemUrl(String subsystemUrl) {
        this.subsystemUrl = subsystemUrl == null ? null : subsystemUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.REMARK
     *
     * @return the value of cs_biz_order.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.REMARK
     *
     * @param remark the value for cs_biz_order.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.RETCODE
     *
     * @return the value of cs_biz_order.RETCODE
     *
     * @mbggenerated
     */
    public Integer getRetcode() {
        return retcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.RETCODE
     *
     * @param retcode the value for cs_biz_order.RETCODE
     *
     * @mbggenerated
     */
    public void setRetcode(Integer retcode) {
        this.retcode = retcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.RETMSG
     *
     * @return the value of cs_biz_order.RETMSG
     *
     * @mbggenerated
     */
    public String getRetmsg() {
        return retmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.RETMSG
     *
     * @param retmsg the value for cs_biz_order.RETMSG
     *
     * @mbggenerated
     */
    public void setRetmsg(String retmsg) {
        this.retmsg = retmsg == null ? null : retmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.ATTACH
     *
     * @return the value of cs_biz_order.ATTACH
     *
     * @mbggenerated
     */
    public String getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.ATTACH
     *
     * @param attach the value for cs_biz_order.ATTACH
     *
     * @mbggenerated
     */
    public void setAttach(String attach) {
        this.attach = attach == null ? null : attach.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.STATUS
     *
     * @return the value of cs_biz_order.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.STATUS
     *
     * @param status the value for cs_biz_order.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.TYPE
     *
     * @return the value of cs_biz_order.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.TYPE
     *
     * @param type the value for cs_biz_order.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.IS_SHOW
     *
     * @return the value of cs_biz_order.IS_SHOW
     *
     * @mbggenerated
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.IS_SHOW
     *
     * @param isShow the value for cs_biz_order.IS_SHOW
     *
     * @mbggenerated
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.RECEIPT_RECEIVE_TIME
     *
     * @return the value of cs_biz_order.RECEIPT_RECEIVE_TIME
     *
     * @mbggenerated
     */
    public Date getReceiptReceiveTime() {
        return receiptReceiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.RECEIPT_RECEIVE_TIME
     *
     * @param receiptReceiveTime the value for cs_biz_order.RECEIPT_RECEIVE_TIME
     *
     * @mbggenerated
     */
    public void setReceiptReceiveTime(Date receiptReceiveTime) {
        this.receiptReceiveTime = receiptReceiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.RECEIPT_ADDR
     *
     * @return the value of cs_biz_order.RECEIPT_ADDR
     *
     * @mbggenerated
     */
    public String getReceiptAddr() {
        return receiptAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.RECEIPT_ADDR
     *
     * @param receiptAddr the value for cs_biz_order.RECEIPT_ADDR
     *
     * @mbggenerated
     */
    public void setReceiptAddr(String receiptAddr) {
        this.receiptAddr = receiptAddr == null ? null : receiptAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.ACCESS_TOKEN
     *
     * @return the value of cs_biz_order.ACCESS_TOKEN
     *
     * @mbggenerated
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.ACCESS_TOKEN
     *
     * @param accessToken the value for cs_biz_order.ACCESS_TOKEN
     *
     * @mbggenerated
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.TOKEN_TIME
     *
     * @return the value of cs_biz_order.TOKEN_TIME
     *
     * @mbggenerated
     */
    public Date getTokenTime() {
        return tokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.TOKEN_TIME
     *
     * @param tokenTime the value for cs_biz_order.TOKEN_TIME
     *
     * @mbggenerated
     */
    public void setTokenTime(Date tokenTime) {
        this.tokenTime = tokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.RECEIPT_OPERATOR
     *
     * @return the value of cs_biz_order.RECEIPT_OPERATOR
     *
     * @mbggenerated
     */
    public String getReceiptOperator() {
        return receiptOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.RECEIPT_OPERATOR
     *
     * @param receiptOperator the value for cs_biz_order.RECEIPT_OPERATOR
     *
     * @mbggenerated
     */
    public void setReceiptOperator(String receiptOperator) {
        this.receiptOperator = receiptOperator == null ? null : receiptOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.ACCESS_SOURCE
     *
     * @return the value of cs_biz_order.ACCESS_SOURCE
     *
     * @mbggenerated
     */
    public String getAccessSource() {
        return accessSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.ACCESS_SOURCE
     *
     * @param accessSource the value for cs_biz_order.ACCESS_SOURCE
     *
     * @mbggenerated
     */
    public void setAccessSource(String accessSource) {
        this.accessSource = accessSource == null ? null : accessSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.PAY_TYPE
     *
     * @return the value of cs_biz_order.PAY_TYPE
     *
     * @mbggenerated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.PAY_TYPE
     *
     * @param payType the value for cs_biz_order.PAY_TYPE
     *
     * @mbggenerated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.IS_GET_RECEIPT
     *
     * @return the value of cs_biz_order.IS_GET_RECEIPT
     *
     * @mbggenerated
     */
    public Integer getIsGetReceipt() {
        return isGetReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.IS_GET_RECEIPT
     *
     * @param isGetReceipt the value for cs_biz_order.IS_GET_RECEIPT
     *
     * @mbggenerated
     */
    public void setIsGetReceipt(Integer isGetReceipt) {
        this.isGetReceipt = isGetReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.IS_UPLOAD
     *
     * @return the value of cs_biz_order.IS_UPLOAD
     *
     * @mbggenerated
     */
    public Integer getIsUpload() {
        return isUpload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.IS_UPLOAD
     *
     * @param isUpload the value for cs_biz_order.IS_UPLOAD
     *
     * @mbggenerated
     */
    public void setIsUpload(Integer isUpload) {
        this.isUpload = isUpload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.UPLOAD_TIME
     *
     * @return the value of cs_biz_order.UPLOAD_TIME
     *
     * @mbggenerated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.UPLOAD_TIME
     *
     * @param uploadTime the value for cs_biz_order.UPLOAD_TIME
     *
     * @mbggenerated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.IS_OUT_PARK
     *
     * @return the value of cs_biz_order.IS_OUT_PARK
     *
     * @mbggenerated
     */
    public Integer getIsOutPark() {
        return isOutPark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.IS_OUT_PARK
     *
     * @param isOutPark the value for cs_biz_order.IS_OUT_PARK
     *
     * @mbggenerated
     */
    public void setIsOutPark(Integer isOutPark) {
        this.isOutPark = isOutPark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.COUPON_TYPE
     *
     * @return the value of cs_biz_order.COUPON_TYPE
     *
     * @mbggenerated
     */
    public String getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.COUPON_TYPE
     *
     * @param couponType the value for cs_biz_order.COUPON_TYPE
     *
     * @mbggenerated
     */
    public void setCouponType(String couponType) {
        this.couponType = couponType == null ? null : couponType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.COUPON_VALUE
     *
     * @return the value of cs_biz_order.COUPON_VALUE
     *
     * @mbggenerated
     */
    public String getCouponValue() {
        return couponValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.COUPON_VALUE
     *
     * @param couponValue the value for cs_biz_order.COUPON_VALUE
     *
     * @mbggenerated
     */
    public void setCouponValue(String couponValue) {
        this.couponValue = couponValue == null ? null : couponValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.IS_STAT
     *
     * @return the value of cs_biz_order.IS_STAT
     *
     * @mbggenerated
     */
    public Integer getIsStat() {
        return isStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.IS_STAT
     *
     * @param isStat the value for cs_biz_order.IS_STAT
     *
     * @mbggenerated
     */
    public void setIsStat(Integer isStat) {
        this.isStat = isStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.CAR_NO
     *
     * @return the value of cs_biz_order.CAR_NO
     *
     * @mbggenerated
     */
    public String getCarNo() {
        return carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.CAR_NO
     *
     * @param carNo the value for cs_biz_order.CAR_NO
     *
     * @mbggenerated
     */
    public void setCarNo(String carNo) {
        this.carNo = carNo == null ? null : carNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.PLATE_COLOR
     *
     * @return the value of cs_biz_order.PLATE_COLOR
     *
     * @mbggenerated
     */
    public String getPlateColor() {
        return plateColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.PLATE_COLOR
     *
     * @param plateColor the value for cs_biz_order.PLATE_COLOR
     *
     * @mbggenerated
     */
    public void setPlateColor(String plateColor) {
        this.plateColor = plateColor == null ? null : plateColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.REFUND_TIME
     *
     * @return the value of cs_biz_order.REFUND_TIME
     *
     * @mbggenerated
     */
    public Date getRefundTime() {
        return refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.REFUND_TIME
     *
     * @param refundTime the value for cs_biz_order.REFUND_TIME
     *
     * @mbggenerated
     */
    public void setRefundTime(Date refundTime) {
        this.refundTime = refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.SYNC_TIME
     *
     * @return the value of cs_biz_order.SYNC_TIME
     *
     * @mbggenerated
     */
    public Date getSyncTime() {
        return syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.SYNC_TIME
     *
     * @param syncTime the value for cs_biz_order.SYNC_TIME
     *
     * @mbggenerated
     */
    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.PREFERENTIAL_MODE
     *
     * @return the value of cs_biz_order.PREFERENTIAL_MODE
     *
     * @mbggenerated
     */
    public String getPreferentialMode() {
        return preferentialMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.PREFERENTIAL_MODE
     *
     * @param preferentialMode the value for cs_biz_order.PREFERENTIAL_MODE
     *
     * @mbggenerated
     */
    public void setPreferentialMode(String preferentialMode) {
        this.preferentialMode = preferentialMode == null ? null : preferentialMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.COUPON_THR_NO
     *
     * @return the value of cs_biz_order.COUPON_THR_NO
     *
     * @mbggenerated
     */
    public String getCouponThrNo() {
        return couponThrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.COUPON_THR_NO
     *
     * @param couponThrNo the value for cs_biz_order.COUPON_THR_NO
     *
     * @mbggenerated
     */
    public void setCouponThrNo(String couponThrNo) {
        this.couponThrNo = couponThrNo == null ? null : couponThrNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.COUPON_THR_TYPE
     *
     * @return the value of cs_biz_order.COUPON_THR_TYPE
     *
     * @mbggenerated
     */
    public Integer getCouponThrType() {
        return couponThrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.COUPON_THR_TYPE
     *
     * @param couponThrType the value for cs_biz_order.COUPON_THR_TYPE
     *
     * @mbggenerated
     */
    public void setCouponThrType(Integer couponThrType) {
        this.couponThrType = couponThrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.MEMBER_NO
     *
     * @return the value of cs_biz_order.MEMBER_NO
     *
     * @mbggenerated
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.MEMBER_NO
     *
     * @param memberNo the value for cs_biz_order.MEMBER_NO
     *
     * @mbggenerated
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.DEDUCTION
     *
     * @return the value of cs_biz_order.DEDUCTION
     *
     * @mbggenerated
     */
    public BigDecimal getDeduction() {
        return deduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.DEDUCTION
     *
     * @param deduction the value for cs_biz_order.DEDUCTION
     *
     * @mbggenerated
     */
    public void setDeduction(BigDecimal deduction) {
        this.deduction = deduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.IS_VALID
     *
     * @return the value of cs_biz_order.IS_VALID
     *
     * @mbggenerated
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.IS_VALID
     *
     * @param isValid the value for cs_biz_order.IS_VALID
     *
     * @mbggenerated
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.IN_ID
     *
     * @return the value of cs_biz_order.IN_ID
     *
     * @mbggenerated
     */
    public String getInId() {
        return inId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.IN_ID
     *
     * @param inId the value for cs_biz_order.IN_ID
     *
     * @mbggenerated
     */
    public void setInId(String inId) {
        this.inId = inId == null ? null : inId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.PREPAY_TIME
     *
     * @return the value of cs_biz_order.PREPAY_TIME
     *
     * @mbggenerated
     */
    public Date getPrepayTime() {
        return prepayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.PREPAY_TIME
     *
     * @param prepayTime the value for cs_biz_order.PREPAY_TIME
     *
     * @mbggenerated
     */
    public void setPrepayTime(Date prepayTime) {
        this.prepayTime = prepayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.CHANNEL_CODE
     *
     * @return the value of cs_biz_order.CHANNEL_CODE
     *
     * @mbggenerated
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.CHANNEL_CODE
     *
     * @param channelCode the value for cs_biz_order.CHANNEL_CODE
     *
     * @mbggenerated
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.CHANNEL_BUS_CODE
     *
     * @return the value of cs_biz_order.CHANNEL_BUS_CODE
     *
     * @mbggenerated
     */
    public String getChannelBusCode() {
        return channelBusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.CHANNEL_BUS_CODE
     *
     * @param channelBusCode the value for cs_biz_order.CHANNEL_BUS_CODE
     *
     * @mbggenerated
     */
    public void setChannelBusCode(String channelBusCode) {
        this.channelBusCode = channelBusCode == null ? null : channelBusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_biz_order.time_end
     *
     * @return the value of cs_biz_order.time_end
     *
     * @mbggenerated
     */
    public Date getTimeEnd() {
        return timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_biz_order.time_end
     *
     * @param timeEnd the value for cs_biz_order.time_end
     *
     * @mbggenerated
     */
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }
}